[package]
name = "rusty_cable"
version = "0.1.0"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
helix = "0.7.5"
reqwest = "0.9"
grpc            = "~0.6"
protobuf        = "~2"
futures         = "~0.1"
futures-cpupool = "~0.1"

[build-dependencies]
protoc-rust-grpc = "0.6.1"
